[package]
name = "chip8rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.10.0"
winit = "0.27.5"
winit_input_helper = "0.13.0"
log = "0.4.17"
byteorder = "1.4.3"